### ISSUE TITLE
Question: Details on date handling

### ISSUE THREAD

**Issue by robmaceachern** [kean/SwiftSQL#1]
Cool library!

I saw the [Advanced Usage](https://github.com/kean/SwiftSQL/blob/0.1.0/Docs/advanced-usage-guide.md) section on how to store dates.

```
extension Date: SQLDataType {
    public func sqlBind(statement: OpaquePointer, index: Int32) {
        sqlite3_bind_double(statement, index, timeIntervalSince1970)
    }

    public static func sqlColumn(statement: OpaquePointer, index: Int32) -> Date {
        Date(timeIntervalSince1970: sqlite3_column_double(statement, index))
    }
}
```

I noticed that it uses `sqlite3_column_double` to store the `timeIntervalSince1970`. Do you know if this approach is compatible with the SQLite [date functions](https://www.sqlite.org/lang_datefunc.html)? An example query would be:

```
SELECT * FROM my_table WHERE my_date < date('now','-30 days')
```

I'm not very familiar with the details of the dates/times in SQLite but my understanding was that the `INTEGER` dates would use the unix epoch and `REAL` dates used a different epoch. From the [datatypes page](https://www.sqlite.org/datatype3.html):

```
TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").
REAL as Julian day numbers, the number of days since noon in Greenwich on November 24, 4714 B.C. according to the proleptic Gregorian calendar.
INTEGER as Unix Time, the number of seconds since 1970-01-01 00:00:00 UTC.
```

Thanks for your time.

**Comment by kean** [comment]
Hi, thank you, that's a great point.

```
SELECT * FROM my_table WHERE my_date < date('now','-30 days')
```

This is not going to work since, as you mentioned, `date` uses IOS-8601 text representation, and it will return something like "2020-04-14".

This is the primary reason behind the design of this library not to make any opinionated decision and not warp SQLite APIs in any way. The guide is only an example and shows one of the potential options.
